UR\Bundle\UserSystem\PublisherBundle\Entity\User:
    exclusion_policy: ALL
    accessor_order: custom
    custom_accessor_order:
        - id
        #- username, email, roles, enabledModules, userRoles, last_login, enabled: inherited from UR\Bundle\UserBundle\Entity\User
        - billingRate
        - firstName
        - lastName
        - company
        - phone
        - city
        - state
        - address
        - postalCode
        - country
        - settings
        - moduleConfigs
        - tagDomain
        - exchanges
        - bidders
    properties:
        id:
            expose: true
            groups: [user.summary, user.uuid, user.detail]
        billingRate:
            expose: true
            groups: [user.detail]
        firstName:
            expose: true
            groups: [user.detail]
        lastName:
            expose: true
            groups: [user.detail]
        company:
            expose: true
            groups: [user.summary, user.uuid, user.detail]
        phone:
            expose: true
            groups: [user.detail]
        city:
            expose: true
            groups: [user.detail]
        state:
            expose: true
            groups: [user.detail]
        address:
            expose: true
            groups: [user.detail]
        postalCode:
            expose: true
            groups: [user.detail]
        country:
            expose: true
            groups: [user.detail]
        settings:
            expose: true
            groups: [user.detail]
        moduleConfigs:
            expose: true
            groups: [user.detail]
        tagDomain:
            expose: true
            groups: [user.detail]
        exchanges:
            expose: true
            groups: [user.summary, user.uuid, user.detail]
        bidders:
            expose: true
            groups: [user.summary, user.uuid, user.detail]
        uuid:
            expose: true
            groups: [user.uuid]
