UR\Entity\Core\DataSet:
    properties:
        name:
            - NotBlank: ~
            - NotNull: ~
#            - Type: string
        dimensions:
            - NotBlank: ~
            - NotNull: ~