UR\Entity\Core\Alert:
    type: entity
    table: core_alert
    repositoryClass: UR\Repository\Core\AlertRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        isRead:
            type: boolean
            option:
                default: false
        code:
            type: integer
        detail:
            type: json_array
            nullable: true
        createdDate:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        type:
            type: string
            length: 20
            nullable: true
        isSent:
            type: boolean
            option:
                default: false
    manyToOne:
        publisher:
            targetEntity: UR\Bundle\UserSystem\PublisherBundle\Entity\User
        dataSource:
            targetEntity: UR\Entity\Core\DataSource
        optimizationIntegration:
            targetEntity: UR\Entity\Core\OptimizationIntegration
            inversedBy: alerts