UR\Entity\Core\DataSourceIntegration:
    type: entity
    table: core_data_source_integration
    repositoryClass: UR\Repository\Core\DataSourceIntegrationRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        params:
            type: json_array
            nullable: true
        schedule:
            type: integer
        active:
            type: boolean
            option:
                default: true
        lastExecutedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
    manyToOne:
        dataSource:
            targetEntity: UR\Entity\Core\DataSource

        integration:
            targetEntity: UR\Entity\Core\Integration
