UR\Entity\Core\DataSourceIntegration:
    type: entity
    table: core_data_source_integration
    repositoryClass: UR\Repository\Core\DataSourceIntegrationRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        params:
            type: json_array
            nullable: true
        schedule:
            type: json_array
            nullable: true
        active:
            type: boolean
            option:
                default: true
        # back fill feature
        backFillStartDate:
            type: date
            nullable: true
        backFillEndDate:
            type: date
            nullable: true
    manyToOne:
        dataSource:
            targetEntity: UR\Entity\Core\DataSource

        integration:
            targetEntity: UR\Entity\Core\Integration

    oneToMany:
        dataSourceIntegrationSchedules:
            targetEntity: UR\Entity\Core\DataSourceIntegrationSchedule
            mappedBy: dataSourceIntegration
            cascade: ['persist', 'detach', 'remove']
            orphanRemoval: true
