services:
    tagcade_user_system_publisher.set_publisher_role_listener:
        class: Tagcade\Bundle\UserSystem\PublisherBundle\EventListener\SetPublisherRoleListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }