Tagcade\Entity\Core\Integration:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [integration.detail]
        name:
            expose: true
            groups: [integration.detail]
        url:
            expose: true
            groups: [integration.detail]
        type:
            expose: true
            groups: [integration.detail]