UR\Entity\Core\IntegrationGroup:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [integrationgroup.detail, integrationgroup.summary]
        name:
            expose: true
            groups: [integrationgroup.detail, integrationgroup.summary]
        integrations:
            expose: true
            groups: [integrationgroup.detail, integrationgroup.summary]