UR\Entity\Core\ReportViewMultiView:
    exclusion_policy: ALL
    properties:
#        id:
#            expose: true
#            groups: [report_view_multi_view.detail, report_view_multi_view.summary]
        filters:
            expose: true
            groups: [report_view_multi_view.detail, report_view_multi_view.summary, report_view_multi_view.share]
        dimensions:
            expose: true
            groups: [report_view_multi_view.detail, report_view_multi_view.summary, report_view_multi_view.share]
        metrics:
            expose: true
            groups: [report_view_multi_view.detail, report_view_multi_view.summary, report_view_multi_view.share]
#        reportView:
#            expose: true
#            groups: [report_view_multi_view.detail, report_view_multi_view.summary]
        subView:
            expose: true
            groups: [report_view_multi_view.detail, report_view_multi_view.summary]
