UR\Entity\Core\ReportViewAddConditionalTransformValue:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [report_view_add_conditional_transform_value.detail, report_view_add_conditional_transform_value.summary]
        name:
            expose: true
            groups: [report_view_add_conditional_transform_value.detail, report_view_add_conditional_transform_value.summary]
        sharedConditions:
            expose: true
            groups: [report_view_add_conditional_transform_value.detail, report_view_add_conditional_transform_value.summary]
        conditions:
            expose: true
            groups: [report_view_add_conditional_transform_value.detail, report_view_add_conditional_transform_value.summary]
        defaultValue:
            expose: true
            groups: [report_view_add_conditional_transform_value.detail, report_view_add_conditional_transform_value.summary]
        createdDate:
            expose: true
            groups: [report_view_add_conditional_transform_value.detail, report_view_add_conditional_transform_value.summary]
