UR\Bundle\UserSystem\PublisherBundle\Entity\User:
    type:  entity
    table: core_user_publisher

    fields:
        uuid:
            type: string
            nullable: true
        firstName:
            type: string
            nullable: true
        lastName:
            type: string
            nullable: true
        company:
            type: string
            nullable: true
        phone:
            type: string
            nullable: true
        billingRate:
            type: decimal
            scale: 4
            nullable: true
        city:
            type: string
            nullable: true
        state:
            type: string
            nullable: true
        address:
            type: string
            nullable: true
        postalCode:
            type: string
            nullable: true
        country:
            type: string
            nullable: true
        settings:
            type: json_array
            nullable: true
        tagDomain:
            type: json_array
            nullable: true
        exchanges:
            type: json_array
            nullable: true
        bidders:
            type: json_array
            nullable: true
        emailSendAlert:
            type: json_array
            nullable: true
    manyToOne:
        masterAccount:
            targetEntity: UR\Bundle\UserSystem\PublisherBundle\Entity\User

    oneToMany:
        userTags:
            targetEntity: UR\Entity\Core\UserTag
            cascade: ['persist', 'detach', 'remove']
            mappedBy: publisher
            orphanRemoval: true