report_api_homepage:
    path:     /reportview/data
    defaults: { _controller: ReportApiBundle:Report:report }
    methods: [POST]

report_api_download:
    path:     /reportview/download
    defaults: { _controller: ReportApiBundle:Report:download }
    methods: [POST]
