report_api_homepage:
    path:     /reportview/data
    defaults: { _controller: ReportApiBundle:Report:report }
    methods: [POST]

report_api_comparison:
    path:     /reportview/comparison
    defaults: { _controller: ReportApiBundle:Report:getReportComparison }
    methods: [POST]

report_api_overview:
    path:     /reportview/overview
    defaults: { _controller: ReportApiBundle:Report:getReportOverview }
    methods: [POST]

report_api_topperformers:
    path:     /reportview/topperformers
    defaults: { _controller: ReportApiBundle:Report:reportTopPerformers }
    methods: [POST]

report_result_api:
    path:     /reportview/{id}/data
    defaults: { _controller: ReportApiBundle:Report:reportResult }
    methods: [POST]

report_api_download:
    path:     /reportview/download
    defaults: { _controller: ReportApiBundle:Report:download }
    methods: [POST]
