report_api_homepage:
    path:     /reportview/data
    defaults: { _controller: ReportApiBundle:Report:report }
    methods: [POST]

report_result_api:
    path:     /reportview/{id}/reportResult
    defaults: { _controller: ReportApiBundle:Report:reportResult }
    methods: [POST]

report_api_download:
    path:     /reportview/download
    defaults: { _controller: ReportApiBundle:Report:download }
    methods: [POST]
