<?php


namespace UR\Service\Report\Groupers;


use UR\Service\DTO\Collection;

class ByDateGrouper extends AbstractGrouper
{
    public function getGroupedReport($groupingFields, Collection $collection, array $metrics)
    {
        parent::getGroupedReport($groupingFields, $collection, $metrics); // TODO: Change the autogenerated stub
    }

}