services:
    # main public services

    tagcade_admin_api.handler.user:
        class: Tagcade\Bundle\AdminApiBundle\Handler\UserHandler
        parent: tagcade.handler.handler_abstract
        public: true
        arguments:
            - @form.factory
            - @tagcade_admin_api.form.type.user
            - @tagcade_user.domain_manager.publisher

    # forms

    tagcade_admin_api.form.type.user:
        class: Tagcade\Bundle\AdminApiBundle\Form\Type\UserFormType
        arguments:
            - @=service('security.context').getToken().getUser()
        tags:
            - { name: form.type, alias: tagcade_form_admin_api_user }

    tagcade_admin_api.event_listener.set_publisher_uuid_listener:
        class: Tagcade\Bundle\AdminApiBundle\EventListener\SetPublisherUuidListener
        tags:
            - { name: doctrine.event_listener, event: prePersist}
