Tagcade\Entity\Core\DataSourceIntegration:
    type: entity
    table: core_data_source_integration
    repositoryClass: Tagcade\Repository\Core\DataSourceIntegrationRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 100
        password:
            type: string
            length: 100
        schedule:
            type: integer

    manyToOne:
        dataSource:
            targetEntity: Tagcade\Entity\Core\DataSource

        integration:
            targetEntity: Tagcade\Entity\Core\Integration
