Tagcade\Entity\Core\Integration:
    type: entity
    table: core_integration
    repositoryClass: Tagcade\Repository\Core\IntegrationRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        url:
            type: string
        type:
            type: string

    manyToOne:
        integrationGroup:
            targetEntity: Tagcade\Entity\Core\IntegrationGroup