parameters:
    # entity class
    ur.entity.core.auto_optimization_config_data_set.class: UR\Entity\Core\AutoOptimizationConfigDataSet

    # form class
    ur.form.type.core.auto_optimization_config_data_set.class: UR\Form\Type\AutoOptimizationConfigDataSetFormType

services:
    # report view dataset
    ur.repository.auto_optimization_config_data_set:
        class: UR\Repository\Core\AutoOptimizationConfigDataSetRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %ur.entity.core.auto_optimization_config_data_set.class%

    ur.form.type.auto_optimization_config_data_set:
        class: %ur.form.type.core.auto_optimization_config_data_set.class%
        tags:
            - { name: form.type, alias: ur_form_auto_optimization_config_data_set }