parameters:
    # entity class
    ur.entity.core.report_schedule.class: UR\Entity\Core\ReportSchedule
    # form class
    ur.form.type.core.report_schedule.class: UR\Form\Type\ReportScheduleFormType

services:
    ur_api.handler.report_schedule:
        class: UR\Handler\HandlerInterface
        factory_service: ur.handler.handler_manager.report_schedule
        factory_method: getHandler
        arguments:
            - @ur.user_role

    ur.repository.report_schedule:
        class: UR\Repository\Core\ReportScheduleRepositoryInterface
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %ur.entity.core.report_schedule.class%

    ur.domain_manager.report_schedule:
        class: UR\DomainManager\ReportScheduleManager
        arguments:
            - @doctrine.orm.entity_manager
            - @ur.repository.report_schedule

    ur.form.type.report_schedule:
        class: %ur.form.type.core.report_schedule.class%
        tags:
            - { name: form.type, alias: ur_form_report_schedule }

    ur.handler.handlers.report_schedule.abstract:
        class: UR\Handler\Handlers\Core\ReportScheduleHandlerAbstract
        parent: ur.handler.role_handler_abstract
        abstract: true
        public: false
        arguments:
            - @ur.form.type.report_schedule
            - @ur.domain_manager.report_schedule

    ur.handler.handlers.report_schedule.admin:
        class: UR\Handler\Handlers\Core\Admin\ReportScheduleHandler
        parent: ur.handler.handlers.report_schedule.abstract
        public: false
        arguments:
            - @ur_user.domain_manager.publisher

    ur.handler.handlers.report_schedule.publisher:
        class: UR\Handler\Handlers\Core\Publisher\ReportScheduleHandler
        parent: ur.handler.handlers.report_schedule.abstract
        public: false

    ur.handler.handler_manager.report_schedule:
        class: UR\Handler\HandlerManager
        arguments:
            - %ur.entity.core.report_schedule.class%
            -
                - @ur.handler.handlers.report_schedule.admin
                - @ur.handler.handlers.report_schedule.publisher