parameters:
    # entity class
    ur.entity.core.learner.class: UR\Entity\Core\Learner

services:
    # integration publisher
    ur.repository.learner:
        class: UR\Repository\Core\LearnerRepositoryInterface
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %ur.entity.core.learner.class%

    ur.domain_manager.learner:
        class: UR\DomainManager\LearnerManager
        arguments:
            - @doctrine.orm.entity_manager
            - @ur.repository.learner