parameters:
    # entity class
    ur.entity.core.linked_map_data_set.class: UR\Entity\Core\LinkedMapDataSet

services:
    ur.repository.linked_map_data_set:
        class: UR\Repository\Core\LinkedMapDataSetRepositoryInterface
        factory:
            - '@doctrine.orm.entity_manager'
            - 'getRepository'
        arguments:
            - '%ur.entity.core.linked_map_data_set.class%'