parameters:
    # entity class
    ur.entity.core.data_source_integration.class: UR\Entity\Core\DataSourceIntegration
    # form class
    ur.form.type.data_source_integration.class: UR\Form\Type\DataSourceIntegrationFormType

services:
    ur_api.handler.data_source_integration:
        class: UR\Handler\HandlerInterface
        factory_service: ur.handler.handler_manager.data_source_integration
        factory_method: getHandler
        arguments:
            - '@ur.user_role'

    ur.repository.data_source_integration:
        class: UR\Repository\Core\DataSourceIntegrationRepositoryInterface
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - '%ur.entity.core.data_source_integration.class%'

    ur.domain_manager.data_source_integration:
        class: UR\DomainManager\DataSourceIntegrationManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@ur.repository.data_source_integration'

    ur.form.type.data_source_integration:
        class: '%ur.form.type.data_source_integration.class%'
        tags:
            - { name: form.type, alias: ur_form_data_source_integration }

    ur.handler.handlers.data_source_integration.abstract:
        class: UR\Handler\Handlers\Core\DataSourceIntegrationHandlerAbstract
        parent: ur.handler.role_handler_abstract
        abstract: true
        public: false
        arguments:
            - '@ur.form.type.data_source_integration'
            - '@ur.domain_manager.data_source_integration'

    ur.handler.handlers.data_source_integration.admin:
        class: UR\Handler\Handlers\Core\Admin\DataSourceIntegrationHandler
        parent: ur.handler.handlers.data_source_integration.abstract
        public: false
        arguments:
            - '@ur_user.domain_manager.publisher'

    ur.handler.handlers.data_source_integration.publisher:
        class: UR\Handler\Handlers\Core\Publisher\DataSourceIntegrationHandler
        parent: ur.handler.handlers.data_source_integration.abstract
        public: false

    ur.handler.handler_manager.data_source_integration:
        class: UR\Handler\HandlerManager
        arguments:
            - '%ur.entity.core.data_source_integration.class%'
            -
                - '@ur.handler.handlers.data_source_integration.admin'
                - '@ur.handler.handlers.data_source_integration.publisher'
