services:
#    tagcade_api.event_listener.update_ad_network_listener:
#        class: Tagcade\Bundle\ApiBundle\EventListener\UpdateAdNetworkListener
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }
#            - { name: doctrine.event_listener, event: preUpdate }
