parameters:
    # entity class
    tagcade.entity.core.data_source_entry.class: Tagcade\Entity\Core\DataSourceEntry
    # form class
    tagcade.form.type.data_source_entry.class: Tagcade\Form\Type\DataSourceEntryFormType

services:
    tagcade_api.handler.data_source_entry:
        class: Tagcade\Handler\HandlerInterface
        factory_service: tagcade.handler.handler_manager.data_source_entry
        factory_method: getHandler
        arguments:
            - @tagcade.user_role

    tagcade.repository.data_source_entry:
        class: Tagcade\Repository\Core\DataSourceEntryRepositoryInterface
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %tagcade.entity.core.data_source_entry.class%

    tagcade.domain_manager.data_source_entry:
        class: Tagcade\DomainManager\DataSourceEntryManager
        arguments:
            - @doctrine.orm.entity_manager
            - @tagcade.repository.data_source_entry

    tagcade.form.type.data_source_entry:
        class: %tagcade.form.type.data_source_entry.class%
        tags:
            - { name: form.type, alias: tagcade_form_data_source_entry }

    tagcade.handler.handlers.data_source_entry.abstract:
        class: Tagcade\Handler\Handlers\Core\DataSourceEntryHandlerAbstract
        parent: tagcade.handler.role_handler_abstract
        abstract: true
        public: false
        arguments:
            - @tagcade.form.type.data_source_entry
            - @tagcade.domain_manager.data_source_entry

    tagcade.handler.handlers.data_source_entry.admin:
        class: Tagcade\Handler\Handlers\Core\Admin\DataSourceEntryHandler
        parent: tagcade.handler.handlers.data_source_entry.abstract
        public: false
        arguments:
            - @tagcade_user.domain_manager.publisher

    tagcade.handler.handlers.data_source_entry.publisher:
        class: Tagcade\Handler\Handlers\Core\Publisher\DataSourceEntryHandler
        parent: tagcade.handler.handlers.data_source_entry.abstract
        public: false

    tagcade.handler.handler_manager.data_source_entry:
        class: Tagcade\Handler\HandlerManager
        arguments:
            - %tagcade.entity.core.data_source_entry.class%
            -
                - @tagcade.handler.handlers.data_source_entry.admin
                - @tagcade.handler.handlers.data_source_entry.publisher
