parameters:
    # entity class
    tagcade.entity.core.data_source.class: Tagcade\Entity\Core\DataSource
    # form class
    tagcade.form.type.core.data_source.class: Tagcade\Form\Type\DataSourceFormType

services:
    tagcade_api.handler.data_source:
        class: Tagcade\Handler\HandlerInterface
        factory_service: tagcade.handler.handler_manager.data_source
        factory_method: getHandler
        arguments:
            - @tagcade.user_role

    tagcade.repository.data_source:
        class: Tagcade\Repository\Core\DataSourceRepositoryInterface
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %tagcade.entity.core.data_source.class%

    tagcade.domain_manager.data_source:
        class: Tagcade\DomainManager\DataSourceManager
        arguments:
            - @doctrine.orm.entity_manager
            - @tagcade.repository.data_source

    tagcade.form.type.data_source:
        class: %tagcade.form.type.core.data_source.class%
        tags:
            - { name: form.type, alias: tagcade_form_data_source }

    tagcade.handler.handlers.data_source.abstract:
        class: Tagcade\Handler\Handlers\Core\DataSourceHandlerAbstract
        parent: tagcade.handler.role_handler_abstract
        abstract: true
        public: false
        arguments:
            - @tagcade.form.type.data_source
            - @tagcade.domain_manager.data_source

    tagcade.handler.handlers.data_source.admin:
        class: Tagcade\Handler\Handlers\Core\Admin\DataSourceHandler
        parent: tagcade.handler.handlers.data_source.abstract
        public: false
        arguments:
            - @tagcade_user.domain_manager.publisher

    tagcade.handler.handlers.data_source.publisher:
        class: Tagcade\Handler\Handlers\Core\Publisher\DataSourceHandler
        parent: tagcade.handler.handlers.data_source.abstract
        public: false

    tagcade.handler.handler_manager.data_source:
        class: Tagcade\Handler\HandlerManager
        arguments:
            - %tagcade.entity.core.data_source.class%
            -
                - @tagcade.handler.handlers.data_source.admin
                - @tagcade.handler.handlers.data_source.publisher