parameters:
    # entity class
    tagcade.entity.core.integration_group.class: Tagcade\Entity\Core\IntegrationGroup
    # form class
    tagcade.form.type.core.integration_group.class: Tagcade\Form\Type\IntegrationGroupFormType

services:
    tagcade_api.handler.integration_group:
        class: Tagcade\Handler\HandlerInterface
        factory_service: tagcade.handler.handler_manager.integration_group
        factory_method: getHandler
        arguments:
            - @tagcade.user_role

    tagcade.repository.integration_group:
        class: Tagcade\Repository\Core\IntegrationGroupRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %tagcade.entity.core.integration_group.class%

    tagcade.domain_manager.integration_group:
        class: Tagcade\DomainManager\IntegrationGroupManager
        arguments:
            - @doctrine.orm.entity_manager
            - @tagcade.repository.integration_group

    tagcade.form.type.integration_group:
        class: %tagcade.form.type.core.integration_group.class%
        tags:
            - { name: form.type, alias: tagcade_form_integration_group }

    tagcade.handler.handlers.integration_group.abstract:
        class: Tagcade\Handler\Handlers\Core\IntegrationGroupHandlerAbstract
        parent: tagcade.handler.role_handler_abstract
        abstract: true
        public: false
        arguments:
            - @tagcade.form.type.integration_group
            - @tagcade.domain_manager.integration_group

    tagcade.handler.handlers.integration_group.admin:
        class: Tagcade\Handler\Handlers\Core\Admin\IntegrationGroupHandler
        parent: tagcade.handler.handlers.integration_group.abstract
        public: false
        arguments:
            - @tagcade_user.domain_manager.publisher

    tagcade.handler.handlers.integration_group.publisher:
        class: Tagcade\Handler\Handlers\Core\Publisher\IntegrationGroupHandler
        parent: tagcade.handler.handlers.integration_group.abstract
        public: false

    tagcade.handler.handler_manager.integration_group:
        class: Tagcade\Handler\HandlerManager
        arguments:
            - %tagcade.entity.core.integration_group.class%
            -
                - @tagcade.handler.handlers.integration_group.admin
                - @tagcade.handler.handlers.integration_group.publisher