parameters:
    # entity class
    tagcade.entity.core.integration.class: Tagcade\Entity\Core\Integration
    # form class
    tagcade.form.type.core.integration.class: Tagcade\Form\Type\IntegrationFormType

services:
    tagcade_api.handler.integration:
        class: Tagcade\Handler\HandlerInterface
        factory_service: tagcade.handler.handler_manager.integration
        factory_method: getHandler
        arguments:
            - @tagcade.user_role

    tagcade.repository.integration:
        class: Tagcade\Repository\Core\IntegrationRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %tagcade.entity.core.integration.class%

    tagcade.domain_manager.integration:
        class: Tagcade\DomainManager\IntegrationManager
        arguments:
            - @doctrine.orm.entity_manager
            - @tagcade.repository.integration

    tagcade.form.type.integration:
        class: %tagcade.form.type.core.integration.class%
        tags:
            - { name: form.type, alias: tagcade_form_integration }

    tagcade.handler.handlers.integration.abstract:
        class: Tagcade\Handler\Handlers\Core\IntegrationHandlerAbstract
        parent: tagcade.handler.role_handler_abstract
        abstract: true
        public: false
        arguments:
            - @tagcade.form.type.integration
            - @tagcade.domain_manager.integration

    tagcade.handler.handlers.integration.admin:
        class: Tagcade\Handler\Handlers\Core\Admin\IntegrationHandler
        parent: tagcade.handler.handlers.integration.abstract
        public: false
        arguments:
            - @tagcade_user.domain_manager.publisher

    tagcade.handler.handlers.integration.publisher:
        class: Tagcade\Handler\Handlers\Core\Publisher\IntegrationHandler
        parent: tagcade.handler.handlers.integration.abstract
        public: false

    tagcade.handler.handler_manager.integration:
        class: Tagcade\Handler\HandlerManager
        arguments:
            - %tagcade.entity.core.integration.class%
            -
                - @tagcade.handler.handlers.integration.admin
                - @tagcade.handler.handlers.integration.publisher