imports:
    #- { resource: services/.yml }

parameters:
    # params

services:
#    tagcade_app.event_listener.adnetwork_change_listener:
#        class: Tagcade\Bundle\AppBundle\EventListener\AdNetworkChangeListener
#        arguments:
#            - @event_dispatcher
#        tags:
#            - { name: doctrine.event_listener, event: onFlush }
#            - { name: doctrine.event_listener, event: postFlush }
#            - { name: doctrine.event_listener, event: preSoftDelete }
