
ur_user_system_publisher_profile_show:
    path: /
    defaults: { _controller: "FOSUserBundle:Profile:show" }
    methods: "GET"

ur_user_system_publisher_profile_edit:
    path: /edit
    defaults: { _controller: "FOSUserBundle:Profile:edit" }
