
ur_user_system_publisher_security_login:
    path: /login
    defaults: { _controller: "FOSUserBundle:Security:login" }

ur_user_system_publisher_security_check:
    path: /login_check
    defaults: { _controller: "FOSUserBundle:Security:check" }
    methods: "POST"

ur_user_system_publisher_security_logout:
    path: /logout
    defaults: { _controller: "FOSUserBundle:Security:logout" }
